-- ============================================================
-- 《电子设备使用指南》数据库结构（schema.sql）
-- 依据：api-contract.md 第 3 节「数据模型」（Day 16 定稿）
-- 日期：2026-10-01（Day 16｜第 3 周）
-- 目标库：CloudBase PostgreSQL（控制台 → 数据管理 → SQL 编辑器）
--
-- 用法：整份粘贴执行。本脚本可反复执行，不会报「已存在」。
--
-- 警告：开头会 DROP 掉这 5 张表，表里的数据会一起消失。
--       本期数据全部来自 seed.sql，随时能重灌，所以是安全的。
--
-- 字段命名与 api-contract.md 的差异（Day 16 已拍板，会回写契约）：
--   desc  -> description   desc 是 SQL 保留字（ORDER BY x DESC），直接用会语法报错
--   time  -> time_cost     time 是 PG 的类型名，容易看混
--   text  -> content       text 同为类型名，text text NOT NULL 读写别扭
--   use   -> purpose       use 容易与 SQL 命令混
--   steps -> step_list     instruments 表里的步骤列，避免与表名 steps 撞车
-- ============================================================


-- ------------------------------------------------------------
-- 第 0 步：清掉旧表 —— 这就是「可重复执行」的实现方式
-- 反着删：先删子表，再删父表；CASCADE 顺带带走依赖它的索引和外键
-- ------------------------------------------------------------
DROP TABLE IF EXISTS tasks       CASCADE;
DROP TABLE IF EXISTS steps       CASCADE;
DROP TABLE IF EXISTS resources   CASCADE;
DROP TABLE IF EXISTS instruments CASCADE;
DROP TABLE IF EXISTS scenes      CASCADE;


-- ------------------------------------------------------------
-- 第 1 张：scenes  场景（主表，4 行）
-- 一行 = 一个场景。它是 steps 和 tasks 的「父表」
-- ------------------------------------------------------------
CREATE TABLE scenes (
  id             text     PRIMARY KEY,
  no             text     NOT NULL UNIQUE,
  name           text     NOT NULL,
  method         text     NOT NULL,
  description    text     NOT NULL,
  device_note    text     NOT NULL DEFAULT 'Android + Windows',
  prerequisite   text     NOT NULL,
  step_count     integer  NOT NULL DEFAULT 0 CHECK (step_count >= 0),
  difficulty     text     NOT NULL DEFAULT '待实测',
  time_cost      text     NOT NULL DEFAULT '待实测',
  measure_status text     NOT NULL DEFAULT 'pending'
                          CHECK (measure_status IN ('measured', 'pending'))
);


-- ------------------------------------------------------------
-- 第 2 张：steps  步骤（子表，20 行 = 4 个场景 x 5 步）
-- scene_id 指向 scenes.id —— 今天要掌握的那条关联字段
-- ------------------------------------------------------------
CREATE TABLE steps (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scene_id         text    NOT NULL REFERENCES scenes (id) ON DELETE CASCADE,
  order_no         integer NOT NULL CHECK (order_no >= 1),
  content          text    NOT NULL,
  difficulty_level integer CHECK (difficulty_level BETWEEN 1 AND 5),
  time_minutes     integer CHECK (time_minutes >= 0),
  caution          text,
  measure_status   text    NOT NULL DEFAULT 'pending'
                           CHECK (measure_status IN ('measured', 'pending')),
  CONSTRAINT steps_scene_order_unique UNIQUE (scene_id, order_no)
);

-- PG 不会给外键自动建索引，手动补一个
CREATE INDEX idx_steps_scene_id ON steps (scene_id);


-- ------------------------------------------------------------
-- 第 3 张：resources  资源入口（独立表，6 行）
-- 谁都不挂靠，每条链接自己就是完整数据
-- ------------------------------------------------------------
CREATE TABLE resources (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text    NOT NULL,
  url     text    NOT NULL CHECK (url ~ '^https://'),
  purpose text    NOT NULL,
  kind    text    NOT NULL CHECK (kind IN ('official', 'community'))
);


-- ------------------------------------------------------------
-- 第 4 张：instruments  仪器操作条目（独立表，34 行 / 6 台仪器）
-- keywords 和 step_list 用 PG 原生数组类型 text[]
-- ------------------------------------------------------------
CREATE TABLE instruments (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_name text    NOT NULL,
  title       text    NOT NULL,
  keywords    text[]  NOT NULL,
  step_list   text[]  NOT NULL,
  source      text    NOT NULL,
  device_type text    NOT NULL CHECK (device_type IN (
                        'dc_power', 'multimeter', 'oscilloscope',
                        'signal_gen', 'lcr', 'curve_tracer'))
);


-- ------------------------------------------------------------
-- 第 5 张：tasks  任务索引（独立表，8 行）
-- scene_id 也指向 scenes.id：8 个跳转按钮 -> 4 个场景
-- ------------------------------------------------------------
CREATE TABLE tasks (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label    text    NOT NULL,
  scene_id text    NOT NULL REFERENCES scenes (id) ON DELETE CASCADE,
  keywords text[]
);

CREATE INDEX idx_tasks_scene_id ON tasks (scene_id);


-- ============================================================
-- 以下是字段注释（COMMENT ON），不影响建表结果。
-- 故意放在最后：万一粘贴时被截断，前面建表的部分已经跑完了。
-- 这一段正好对上今天的「余力加练：给字段加注释」。
-- ============================================================

COMMENT ON TABLE scenes IS '场景主表：一行一个使用场景（S1-S4）';
COMMENT ON COLUMN scenes.id             IS '场景主键，形如 scene-1，沿用静止站既有值以兼容已公开的地址';
COMMENT ON COLUMN scenes.no             IS '显示编号 S1-S4，唯一';
COMMENT ON COLUMN scenes.name           IS '场景名，如「实验数据 / 板书传电脑」';
COMMENT ON COLUMN scenes.method         IS '本场景用的传法，如 USB 数据线 / LocalSend 局域网';
COMMENT ON COLUMN scenes.description    IS '一句话描述（原字段名 desc，desc 是 SQL 保留字）';
COMMENT ON COLUMN scenes.device_note    IS '适用设备/系统标注，本期固定 Android + Windows';
COMMENT ON COLUMN scenes.prerequisite   IS '前置条件，必填（PRD AC-09 要求）';
COMMENT ON COLUMN scenes.step_count     IS '步骤数，与 steps 表中该场景的行数一致';
COMMENT ON COLUMN scenes.difficulty     IS '场景级难度，未实测时固定为「待实测」，不编数字';
COMMENT ON COLUMN scenes.time_cost      IS '场景级耗时，未实测时固定为「待实测」（原字段名 time）';
COMMENT ON COLUMN scenes.measure_status IS '难度与耗时是否已实测：measured 已实测 / pending 待实测';

COMMENT ON TABLE steps IS '步骤子表：一行一个步骤，通过 scene_id 挂在场景下';
COMMENT ON COLUMN steps.id               IS '自增主键';
COMMENT ON COLUMN steps.scene_id         IS '外键，指向 scenes.id；这就是子表与主表的关联字段';
COMMENT ON COLUMN steps.order_no         IS '第几步，从 1 开始；同一场景内不允许重号';
COMMENT ON COLUMN steps.content          IS '步骤正文，一步只说一件事（原字段名 text）';
COMMENT ON COLUMN steps.difficulty_level IS '难度星级 1-5；未实测存 NULL，不编数字';
COMMENT ON COLUMN steps.time_minutes     IS '预计耗时（分钟）；未实测存 NULL，不编数字';
COMMENT ON COLUMN steps.caution          IS '注意事项 / 常见的坑，可空';
COMMENT ON COLUMN steps.measure_status   IS '难度与耗时是否已实测：measured / pending';

COMMENT ON TABLE resources IS '资源入口表：一行一条外部链接';
COMMENT ON COLUMN resources.id      IS '自增主键';
COMMENT ON COLUMN resources.name    IS '资源名';
COMMENT ON COLUMN resources.url     IS '外链地址，约束只允许 https';
COMMENT ON COLUMN resources.purpose IS '用途一句话（原字段名 use）';
COMMENT ON COLUMN resources.kind    IS '类型：official 官方 / community 社区（本期 6 条全为 official）';

COMMENT ON TABLE instruments IS '仪器操作条目表：从厂商说明书 PDF 提炼的常用操作';
COMMENT ON COLUMN instruments.id          IS '自增主键';
COMMENT ON COLUMN instruments.device_name IS '仪器类型 + 型号，如「示波器 GDS-1102B」；仅展示，不参与搜索匹配';
COMMENT ON COLUMN instruments.title       IS '操作名一句话；参与搜索匹配';
COMMENT ON COLUMN instruments.keywords    IS '触发关键词数组，含中文别名与英文小写；参与搜索匹配';
COMMENT ON COLUMN instruments.step_list   IS '分步清单数组，一步一条（原字段名 steps，避免与表名撞车）';
COMMENT ON COLUMN instruments.source      IS '出处：说明书名称 + PDF 实际页码，便于回查';
COMMENT ON COLUMN instruments.device_type IS '仪器类型枚举，供类型筛选：dc_power/multimeter/oscilloscope/signal_gen/lcr/curve_tracer';

COMMENT ON TABLE tasks IS '任务索引表：搜索框与跳转按钮共用的任务清单';
COMMENT ON COLUMN tasks.id       IS '自增主键';
COMMENT ON COLUMN tasks.label    IS '显示名，如「拍板书」';
COMMENT ON COLUMN tasks.scene_id IS '外键，指向 scenes.id：点击后跳到哪个场景';
COMMENT ON COLUMN tasks.keywords IS '搜索匹配关键词；现无真实数据，存 NULL，不编';
